FROM tensorflow/tensorflow:latest

WORKDIR /usr/src/app

COPY . .

RUN apt-get update
RUN python -m pip install --upgrade pip
RUN pip install -r /usr/src/app/requirements_docker.txt

ENTRYPOINT [ "python3", "/usr/src/app/trainer.py" ]


